const q = (s) => `'${String(s).replace(/'/g, "''")}'`

export function serializeAbout(about) {
  const lines = [`name: ${q(about.name)}`]
  for (const key of ['tagline', 'instagram', 'email']) {
    if (about[key]) lines.push(`${key}: ${q(about[key])}`)
  }
  if (about.portrait) {
    lines.push(`portraitSrc: ${q(about.portrait.src)}`)
    if (about.portrait.srcset)
      lines.push(`portraitSrcset: ${q(about.portrait.srcset)}`)
    lines.push(`portraitWidth: ${about.portrait.width}`)
    lines.push(`portraitHeight: ${about.portrait.height}`)
    lines.push(`portraitBlur: ${q(about.portrait.blurDataURL)}`)
  }

  const fm = ['---', ...lines, '---'].join('\n')
  const comment =
    '{/* Generated by sync-projects — edit content/_about/info.md, not here. */}'
  const body = about.body ? `\n${about.body}\n` : '\n'
  return `${fm}\n\n${comment}\n${body}`
}
