import { test } from 'node:test'
import assert from 'node:assert/strict'
import { serializeProject } from './mdx.mjs'

const project = {
  slug: 'demo',
  title: "Painter's Light",
  year: '2026',
  publishedAt: '2026-05-26',
  summary: 'A summary.',
  medium: 'Oil on linen',
  body: 'The write-up.',
  images: [
    { src: 'https://x.r2.dev/demo/a.avif', width: 6000, height: 4000, blurDataURL: 'data:image/jpeg;base64,AAA', thumb: true },
    { src: 'https://x.r2.dev/demo/b.avif', width: 4000, height: 6000, blurDataURL: 'data:image/jpeg;base64,BBB' },
  ],
}

test('emits frontmatter with present fields only', () => {
  const out = serializeProject(project)
  assert.match(out, /^---\n/)
  assert.match(out, /\ntitle: 'Painter''s Light'\n/)
  assert.match(out, /\nmedium: 'Oil on linen'\n/)
  assert.doesNotMatch(out, /\nlocation:/)
})

test('emits images as block objects with thumb flag', () => {
  const out = serializeProject(project)
  assert.match(out, /src: 'https:\/\/x\.r2\.dev\/demo\/a\.avif'/)
  assert.match(out, /thumb: true/)
  assert.match(out, /width: 6000/)
})

test('includes the generated-file comment and body', () => {
  const out = serializeProject(project)
  assert.match(out, /\{\/\* Generated by sync-projects/)
  assert.match(out, /The write-up\.\n?$/)
})

test('escapes single quotes in body-free strings', () => {
  const out = serializeProject({ ...project, title: "It's Fine" })
  assert.match(out, /title: 'It''s Fine'/)
})

test('serializeProject emits srcset when present', () => {
  const out = serializeProject({
    title: 'Lit',
    images: [
      {
        src: 'https://pub.example.dev/_web/lit/one-abc-1280.avif',
        width: 1280,
        height: 800,
        blurDataURL: 'data:image/jpeg;base64,AAA',
        srcset: 'https://pub.example.dev/_web/lit/one-abc-640.avif 640w',
      },
    ],
  })
  assert.match(out, /srcset: 'https:\/\/pub\.example\.dev\/_web\/lit\/one-abc-640\.avif 640w'/)
})

test('generated files point the reader at content/, not the dead R2 bucket', async () => {
  const { serializeAbout } = await import('./about.mjs')
  const project = serializeProject({
    title: 'X',
    images: [{ src: '/a.avif', width: 1, height: 1, blurDataURL: 'x' }],
  })
  const about = serializeAbout({ name: 'Dave', body: '' })

  for (const [name, out] of [['project', project], ['about', about]]) {
    assert.doesNotMatch(out, /R2/, `${name} still mentions R2`)
    assert.match(out, /content\//, `${name} must say where to edit instead`)
  }
  assert.match(project, /content\/<project>\/info\.md/)
  assert.match(about, /content\/_about\/info\.md/)
})
