const q = (s) => `'${String(s).replace(/'/g, "''")}'`

function frontmatterLines(p) {
  const lines = [`title: ${q(p.title)}`]
  if (p.year) lines.push(`year: ${q(p.year)}`)
  if (p.publishedAt) lines.push(`publishedAt: ${q(p.publishedAt)}`)
  if (p.summary) lines.push(`summary: ${q(p.summary)}`)
  if (p.medium) lines.push(`medium: ${q(p.medium)}`)
  if (p.location) lines.push(`location: ${q(p.location)}`)
  return lines
}

function imageBlock(img) {
  const lines = [
    `  - src: ${q(img.src)}`,
    `    alt: ''`,
    `    width: ${img.width}`,
    `    height: ${img.height}`,
    `    blurDataURL: ${q(img.blurDataURL)}`,
  ]
  if (img.srcset) lines.push(`    srcset: ${q(img.srcset)}`)
  if (img.thumb) lines.push(`    thumb: true`)
  return lines.join('\n')
}

export function serializeProject(p) {
  const fm = [
    '---',
    ...frontmatterLines(p),
    'images:',
    ...p.images.map(imageBlock),
    '---',
  ].join('\n')

  const comment =
    '{/* Generated by sync-projects — edit content/<project>/info.md, not here. */}'
  const body = p.body ? `\n${p.body}\n` : '\n'
  return `${fm}\n\n${comment}\n${body}`
}
